# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=75)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
