# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 22, 19, 31, 42, 20879)),
        ),
    ]
