# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160722_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 22, 20, 17, 45, 440832)),
        ),
    ]
